version: '3.8'

services:
  server:
    image: 127.0.0.1:5000/server_image:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - '3000:3000'
    networks:
      - app-network

  client:
    image: 127.0.0.1:5000/client_image:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    ports:
      - '5173:5173'
    networks:
      - app-network

  postgres:
    image: postgres:16.2
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - '80:80'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
