version: '3'

services:
  http:
    image: nginx:1.25
    ports:
      - 8080:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - reseau
    depends_on:
      - script

  script:
    build: .
    networks:
      - reseau
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - data

  data:
    image: mariadb:10.2
    networks:
      - reseau
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./data/:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:2.430-jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home


volumes:
  data:
  jenkins_home:

networks:
  reseau: